### ISSUE TITLE
[Errno 2] No such file or directory: 'projectname\\win.exe.manifest'

### ISSUE THREAD

**Issue by valdemonte** [JMSwag/PyUpdater#304]
Hi, 
I recently cleaned my machine and update the python distribution. After the update, I was not able to build my application anymore using PyUpdater. Here under the error returned:

![Capture d’écran 2021-11-03 102305](https://user-images.githubusercontent.com/93647186/140036462-68b20901-3e70-4485-a569-cf7a47f72c8b.png)
.

Trying to troubleshoot the error, I found that rolling back to PyInstaller 4.0 solve the problem.

Python: 3.7.11
PyUpdater: 4.0
PyInstaller: 4.6 not working, 4.0 working

**Comment by Mouaz-Alnouri** [comment]
i had the same problem.

**Comment by dimitriepirghie** [comment]
I have the same problem.

If splash screen feature is needed it work with `pyinstaller==4.4`, so it's seems the problem is introduced in version 4.5 or 4.6.

**Comment by bryan-koroleski-fivestars** [comment]
This is caused by a change introduced in PyInstaller 4.6: https://pyinstaller.readthedocs.io/en/stable/CHANGES.html#id2

> (Windows) Embed the manifest into generated onedir executables by default, in order to avoid potential issues when user renames the executable (e.g., the manifest not being found anymore due to activation context caching when user renames the executable and attempts to run it before also renaming the manifest file). The old behavior of generating the external manifest file in onedir mode can be re-enabled using the --no-embed-manifest command-line switch, or via the embed_manifest=False argument to EXE() in the .spec file. [(#6248)](https://github.com/pyinstaller/pyinstaller/issues/6248)

**Comment by dennisvang** [comment]
The PR above should fix this. 

In the meantime, the easiest workaround I guess is to set `EXE(..., embed_manifest=False)` in your .spec file, as suggested in the quote above.
