### ISSUE TITLE
Discord server for support and smaller discussions

### ISSUE THREAD

**Issue by JessicaTegner** [JMSwag/PyUpdater#321]
hi there.
I've seen the trent of projects using a chat platform to provide support, have smaller discussions with maintainers and contributers, community and others.
Would this be something you would be interested in @JMSwag 
I think it would help speed the development circle up, and provide a place, where people can come and ask for help / support.

**Comment by JMSwag** [comment]
~https://discord.gg/g9tBYRU3kP~

I've setup the github discussions feature. It's easier for me if everything in one place.

**Comment by JessicaTegner** [comment]
nice.
Then just make sure it's a link that doesn't expire, and have unlimited uses, and then add it to the readme :)

**Comment by diVineProportion** [comment]
Discord is cool. For future reference, were you familiar with Gitter @JMSwag? Also, too little too late, but github finally added a place


![aHLpLmC5AGrW](https://user-images.githubusercontent.com/38984875/149513304-f62cd073-96bc-41fb-8d3d-4bececf0319a.png)

**Comment by JMSwag** [comment]
@diVineProportion Discussions have been enabled in the repo. Thanks for the heads up!
